Thu Sep 19 15:26:35 MST 2024
Initiating script
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ ggplot2::annotate() masks ctmm::annotate()
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::lag()        masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘data.table’

The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year

The following objects are masked from ‘package:dplyr’:

    between, first, last

The following object is masked from ‘package:purrr’:

    transpose

[1] "/home/u15/mmercer3/proj/bobcat_chapter/data/Bobcat_Individuals/range_resident/dave.csv"
     [,1]                                
[1,] "Data loaded at 2024-09-19 15:26:44"
Minimum sampling interval of 59.4 minutes in unknown
Warning message:
In as.telemetry.data.frame(individual_gps) :
  No MoveBank or GBIF identification found. Assuming data corresponds to one indiviudal.
DOP values missing. Assuming DOP=1.
[1] "BC_#4_Dave_(11/20/20_-_1/29/21)"
[1] "Telemetry object created at 2024-09-19 15:26:47.052045"
[1] "CTMM fit at 2024-09-19 15:31:25.188945"
$name
[1] "OUf anisotropic error"

$DOF
     mean      area diffusion     speed 
114.48526 131.08644  36.47325  11.71667 

$CI
                                        low       est      high
area (square kilometers)          18.766857 22.444381 26.446066
τ (hours)                          1.948056  2.645744  3.593307
speed (kilometers/day)            12.838424 17.943199 23.039431
diffusion (square kilometers/day)  8.974563 12.781390 17.250721

[1] "home range created"
Error in gzfile(file, "wb") : cannot open the connection
Calls: save -> gzfile
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file 'data/Model_Fit_Results/BC_#4_Dave_(11/20/20_-_1/29/21).Rda', probable reason 'No such file or directory'
Execution halted
Script complete
Thu Sep 19 15:31:26 MST 2024
